language: node_js
node_js:
  - '6'
services: mongodb

cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - nohup bash -c "npm run test:server 2>&1 &" && sleep 3
script:
  - npm run lint
  - npm test
